/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Home: () => import('#controllers/home_controller'),
  ShowPost: () => import('#controllers/show_post_controller'),
  ShowPosts: () => import('#controllers/show_posts_controller'),
}
