/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="./manifest.d.ts" />
import type { InferData, InferVariants } from '@adonisjs/core/types/transformers'
import type { InferSharedProps } from '@adonisjs/inertia/types'
import type ExperienceTransformer from '#transformers/experience_transformer'
import type PostTransformer from '#transformers/post_transformer'
import type ProjectTransformer from '#transformers/project_transformer'
import type InertiaMiddleware from '#middleware/inertia_middleware'

export namespace Data {
  export type Experience = InferData<ExperienceTransformer>
  export namespace Experience {
    export type Variants = InferVariants<ExperienceTransformer>
  }
  export type Post = InferData<PostTransformer>
  export namespace Post {
    export type Variants = InferVariants<PostTransformer>
  }
  export type Project = InferData<ProjectTransformer>
  export namespace Project {
    export type Variants = InferVariants<ProjectTransformer>
  }
  export type SharedProps = InferSharedProps<InertiaMiddleware>
}
